env = Environment()
targets = { "server" : "server.cpp" , "tcp-client" : "tcp-client.cpp", "udp-client" : "udp-client.cpp"}
linkflags = ''
if int(ARGUMENTS.get('static', 0)):
    linkflags = '-Wl,-static -static-libgcc'
common_sources = []
CommonObjects = env.Object(common_sources)
for target, file in targets.iteritems():
    env.Program(target = target, source = [file, CommonObjects], LINKFLAGS=linkflags, LIBS = [ 'pthread', 'boost_system'])
