import os
env = Environment(ENV = os.environ, CCFLAGS='-std=c++11', LIBPATH=['/usr/local/lib'])
targets = {"server" : "main.cpp"}
linkflags = ''
common_sources = ['log.cpp', 'resource.cpp']
CommonObjects = env.Object(common_sources)
for target, file in targets.iteritems():
    env.Program(target = target, 
                source = [file, CommonObjects], 
                LINKFLAGS=linkflags, 
                LIBS = ['wt','wtdbo','wtdbomysql','wtdbosqlite3','wthttp','wttest','boost_thread-mt', 'boost_signals-mt','rt'])
env.Clean('.', '.sconsign.dblite')
