import os
env = Environment(ENV = os.environ, CCFLAGS='-DBOOST_SIGNALS_NO_DEPRECATION_WARNING -O2 -std=c++11', LIBPATH=['/usr/lib'])
targets = {"server" : "main.cpp"}
linkflags = ''
common_sources = ['log.cpp', 'resource.cpp']
CommonObjects = env.Object(common_sources)
for target, file in targets.iteritems():
    env.Program(target = target, 
                source = [file, CommonObjects], 
                LINKFLAGS=linkflags, 
                LIBS = ['wt','wthttp','boost_thread','boost_system','rt'])
env.Clean('.', '.sconsign.dblite')
