import os
env = Environment(ENV = os.environ, CCFLAGS='-g -std=c++11', LIBPATH=['/usr/lib'])
targets = {"srt" : "srt.cc"}
linkflags = ''
if int(ARGUMENTS.get('static', 0)):
    linkflags = '-Wl,-static -static-libgcc'
common_sources = []
CommonObjects = env.Object(common_sources)
for target, file in targets.iteritems():
    env.Program(target = target, source = [file, CommonObjects], LINKFLAGS=linkflags, LIBS = ['boost_regex', 'rt'])
env.Clean('.', '.sconsign.dblite')
