env = Environment()
targets = { "test" : "test.c"}
linkflags = ''
if int(ARGUMENTS.get('static', 0)):
    linkflags = '-Wl,-static -static-libgcc'
common_sources = []
CommonObjects = env.Object(common_sources)
for target, file in targets.iteritems():
    env.Program(target = target, source = [file, CommonObjects], CPPPATH=['/home/irocha/git/hiredis'], LIBPATH=['/usr/local/lib'], LINKFLAGS=linkflags, LIBS = [ 'hiredis', 'event', 'rt', 'pthread'])
env.Clean('.', '.sconsign.dblite')
