import os
env = Environment(ENV = os.environ, CCFLAGS='-g -std=c++0x', CPPPATH=['/usr/include/hiredis'], LIBPATH=['/usr/lib'])
targets = {"server" : "server.cc"}
linkflags = '-g'
if int(ARGUMENTS.get('static', 0)):
    linkflags = '-g -Wl,-static -static-libgcc'
common_sources = []
CommonObjects = env.Object(common_sources)
for target, file in targets.iteritems():
    env.Program(target = target, source = [file, CommonObjects], 
	            LINKFLAGS=linkflags, 
                LIBS = ['event', 'hiredis', 'pthread', 'rt'])
env.Clean('.', '.sconsign.dblite')
