import os
env = Environment(ENV = os.environ, CCFLAGS='-g -std=c++0x', LIBPATH=['/usr/local/lib'])
targets = {"sniffer" : "sniffer.cc"}
linkflags = '-Wl,-static -static-libgcc'
common_sources = []
CommonObjects = env.Object(common_sources)
for target, file in targets.iteritems():
    env.Program(target = target, source = [file, CommonObjects], LINKFLAGS=linkflags, LIBS = ['pthread', 'rt', 'tins', 'pcap'])
env.Clean('.', '.sconsign.dblite')
