import os
env = Environment(ENV = os.environ, CCFLAGS='-g -std=c++11', LIBPATH=['/usr/local/lib'])
targets = {"sniffer" : "sniffer.cpp"}
linkflags = '-Wl,-static -static-libgcc'
common_sources = ['tcpcap_stream.cpp']
CommonObjects = env.Object(common_sources)
for target, file in targets.iteritems():
    env.Program(target = target, source = [file, CommonObjects], LINKFLAGS=linkflags, LIBS = ['boost_iostreams-mt', 'boost_regex-mt', 'rt', 'tins', 'pcap', 'pthread'])
env.Clean('.', '.sconsign.dblite')
