import os
env = Environment(ENV = os.environ, CCFLAGS='-std=c++11', LIBPATH=['/usr/local/lib'])
targets = {"hello" : "hello.cc"}
linkflags = ''
common_sources = []
CommonObjects = env.Object(common_sources)
for target, file in targets.iteritems():
    env.Program(target = target, 
                source = [file, CommonObjects], 
                LINKFLAGS=linkflags, 
                LIBS = ['wt','wtdbo','wtdbomysql','wtdbosqlite3','wthttp','wttest','boost_signals-mt','rt'])
env.Clean('.', '.sconsign.dblite')
